version: '3.1'

services:

  mongo:
    image: mongo:2.6.4 # https://hub.docker.com/_/mongo/tags?page=&page_size=&ordering=&name=2.6.4
    restart: always
    ports:
      - 27017:27017

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
